FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './results' # Testing files saving path

DATASET:
  SMPL_PATH: './deps/smpl'
  TRANSFORM_PATH: './mld/transforms/'
  WORD_VERTILIZER_PATH: './deps/t2m/glove/'
  KIT:
    ROOT: './motionml_kit' # KIT directory
    SPLIT_ROOT: './motionml_kit' # KIT splits directory
  HUMANML3D:
    ROOT: './motionml' # HumanML3D directory
    SPLIT_ROOT: './motionml' # HumanML3D splits directory

model:
  bert_path: './deps/distilbert-base-uncased' # bert model path for all text encoders
  clip_path: './deps/clip-vit-large-patch14' # bert model path for all text encoders
  t2m_path: './deps/t2m/t2m'

  humanact12_rec_path: './deps/actionrecognition'
  uestc_rec_path: './deps/actionrecognition'
  # Set model path separately for different encoders
  # TEXT_ENCODER:
  #   MODELPATH: './deps/distilbert-base-uncased' # bert model path for text encoder
  # TEXT_STYLE_ENCODER:
  #   MODELPATH: './deps/distilbert-base-uncased' # bert model path for text style encoder
  # TEXT_CONTENT_ENCODER:
  #   MODELPATH: './deps/distilbert-base-uncased' # bert model path for text content encoder

RENDER:
  BLENDER_PATH: '/apdcephfs/share_1227775/mingzhenzhu/jiangbiao/libs/blender-2.93.2-linux-x64/blender'
  FACES_PATH: '/apdcephfs/share_1227775/shingxchen/AIMotion/TMOSTData/deps/smplh/smplh.faces'
  FOLDER: ./animations
